// <auto-generated />
namespace SpletnaDrazba.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SpremenjenaPonudba : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpremenjenaPonudba));
        
        string IMigrationMetadata.Id
        {
            get { return "201701180920348_SpremenjenaPonudba"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
